project_id = "rprvesldwwgotoqtuhrz"

[functions.get-availability]
verify_jwt = false

[functions.create-booking]
verify_jwt = false

[functions.chatbot-integration]
verify_jwt = false

[functions.provision-talkmap]
verify_jwt = false
