version: '3.8'

services:
  frontend:
    build:
      context: ./
      dockerfile: deployment/Dockerfile
      args:
        - VITE_SUPABASE_URL=${VITE_SUPABASE_URL}
        - VITE_SUPABASE_ANON_KEY=${VITE_SUPABASE_ANON_KEY}
    networks:
      - zailom-booking
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.zailom-booking.rule=Host(`booking.zailom.com`)"
      - "traefik.http.routers.zailom-booking.entrypoints=websecure"
      - "traefik.http.routers.zailom-booking.tls=true"
      - "traefik.http.routers.zailom-booking.tls.certresolver=letsencrypt"
      - "traefik.http.services.zailom-booking.loadbalancer.server.port=80"
    restart: always

networks:
  zailom-booking:
    external: true
